// Generated by gencpp from file semantic_planning_msgs/SceneClassification.msg
// DO NOT EDIT!


#ifndef SEMANTIC_PLANNING_MSGS_MESSAGE_SCENECLASSIFICATION_H
#define SEMANTIC_PLANNING_MSGS_MESSAGE_SCENECLASSIFICATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace semantic_planning_msgs
{
template <class ContainerAllocator>
struct SceneClassification_
{
  typedef SceneClassification_<ContainerAllocator> Type;

  SceneClassification_()
    : header()
    , class(0)  {
    }
  SceneClassification_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , class(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _class_type;
  _class_type class;



  enum {
    UNKNOWN = 0u,
    HALLWAY = 1u,
    LAB = 2u,
    LOBBY = 3u,
    KITCHEN = 4u,
    OFFICE = 5u,
    PARKING_LOT = 6u,
  };


  typedef boost::shared_ptr< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> const> ConstPtr;

}; // struct SceneClassification_

typedef ::semantic_planning_msgs::SceneClassification_<std::allocator<void> > SceneClassification;

typedef boost::shared_ptr< ::semantic_planning_msgs::SceneClassification > SceneClassificationPtr;
typedef boost::shared_ptr< ::semantic_planning_msgs::SceneClassification const> SceneClassificationConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace semantic_planning_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'semantic_planning_msgs': ['/code/software/ros_workspace/semantic_planning_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4292493ef08199bcfaac2c65bb4210c3";
  }

  static const char* value(const ::semantic_planning_msgs::SceneClassification_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4292493ef08199bcULL;
  static const uint64_t static_value2 = 0xfaac2c65bb4210c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "semantic_planning_msgs/SceneClassification";
  }

  static const char* value(const ::semantic_planning_msgs::SceneClassification_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message header\n\
Header header\n\
\n\
# scene class. Accepts value from the scene classes enum below\n\
uint8 class\n\
\n\
# ENUM: scene classes\n\
uint8 UNKNOWN=0\n\
uint8 HALLWAY=1\n\
uint8 LAB=2\n\
uint8 LOBBY=3\n\
uint8 KITCHEN=4\n\
uint8 OFFICE=5\n\
uint8 PARKING_LOT=6\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::semantic_planning_msgs::SceneClassification_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SceneClassification_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::semantic_planning_msgs::SceneClassification_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::semantic_planning_msgs::SceneClassification_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "class: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.class);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEMANTIC_PLANNING_MSGS_MESSAGE_SCENECLASSIFICATION_H
