set(_CATKIN_CURRENT_PACKAGE "semantic_planning_msgs")
set(semantic_planning_msgs_VERSION "0.0.0")
set(semantic_planning_msgs_MAINTAINER "Andrea F Daniele <afdaniele@ttic.edu>")
set(semantic_planning_msgs_PACKAGE_FORMAT "1")
set(semantic_planning_msgs_BUILD_DEPENDS "message_generation" "roscpp" "std_msgs" "geometry_msgs" "sensor_msgs")
set(semantic_planning_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "sensor_msgs")
set(semantic_planning_msgs_BUILDTOOL_DEPENDS "catkin")
set(semantic_planning_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(semantic_planning_msgs_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "sensor_msgs")
set(semantic_planning_msgs_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "sensor_msgs")
set(semantic_planning_msgs_TEST_DEPENDS )
set(semantic_planning_msgs_DOC_DEPENDS )
set(semantic_planning_msgs_URL_WEBSITE "")
set(semantic_planning_msgs_URL_BUGTRACKER "")
set(semantic_planning_msgs_URL_REPOSITORY "")
set(semantic_planning_msgs_DEPRECATED "")